from .config import (
    SCREEN_WIDTH, SCREEN_HEIGHT, FPS,
    WHITE, BLACK, RED, BLUE, GREEN, YELLOW, GRAY, ORANGE,
    LIGHT_BLUE, DARK_BLUE, DARK_RED,
    POWERUP_SHIELD, POWERUP_SPEED, POWERUP_SLOW, POWERUP_SCORE,
    POWERUP_CONFIG
)

__all__ = [
    'SCREEN_WIDTH', 'SCREEN_HEIGHT', 'FPS',
    'WHITE', 'BLACK', 'RED', 'BLUE', 'GREEN', 'YELLOW', 'GRAY', 'ORANGE',
    'LIGHT_BLUE', 'DARK_BLUE', 'DARK_RED',
    'POWERUP_SHIELD', 'POWERUP_SPEED', 'POWERUP_SLOW', 'POWERUP_SCORE',
    'POWERUP_CONFIG'
]
